[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "monkai-agent"
version = "0.1.0"
description = "MonkAI Agent Framework"
requires-python = ">=3.8"

[tool.hatch.build.targets.wheel]
packages = ["libs/*"]
