[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "monkai-agent-all"
version = "0.1.0"
description = "MonkAI Agent Framework"
requires-python = ">=3.8"

[tool.hatch.build]
packages = [
    "libs/monkai_agent",
    "libs/monkai_agent_groq"
]

[tool.hatch.build.targets.wheel]
packages = ["libs"]

[tool.hatch.build.targets.wheel.force-include]
"libs/monkai_agent_groq/monkai_agent" = "monkai_agent/groq"