[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "monkai-agent"
version = "0.1.0"
description = "MonkAI Agent Framework"
requires-python = ">=3.8"
dependencies = [
    "openai>=1.0.0",
    "groq>=0.3.0"
]

[tool.hatch.build]
packages = ["libs/monkai_agent"]

[tool.hatch.build.targets.wheel]
packages = ["libs/monkai_agent"]

[project.optional-dependencies]
groq = ["monkai-agent-groq"]