[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "monkai"
version = "0.1.0"
description = "MonkAI Agent Framework with Groq Integration"
requires-python = ">=3.8"
dependencies = [
    "pydantic>=2.0.0",
    "typing-extensions>=4.0.0",
    "openai>=1.0.0",
    "groq"
]

[tool.hatch.build]
packages = [
    "libs/monkai_agent/monkai_agent",
    "libs/monkai_agent_groq/monkai_agent_groq"
]

[tool.hatch.build.targets.wheel]
packages = [
    "libs/monkai_agent/monkai_agent",
    "libs/monkai_agent_groq/monkai_agent_groq"
]

[tool.hatch.build.targets.wheel.force-include]
"libs/monkai_agent/monkai_agent" = "monkai_agent"
"libs/monkai_agent_groq/monkai_agent_groq" = "monkai_agent/groq"